# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        name: checkout the code
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          #password: ${{ secrets.GH_PASSWORD }}
      - name: docker build
        run: |
          docker build . --file Dockerfile --build-arg PYTHON_VERSION=3.8 --tag ghcr.io/atiframzan89/docker-python:latest
      - name: docker push
        run: |
          docker push ghcr.io/atiframzan89/docker-python:latest
      
      - name: Deploy to EC2 Instance
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: docker rm -f python-docker || true && docker run -d --name python-docker -p 5000:5000 ghcr.io/atiframzan89/docker-python:latest
          host: 52.0.82.174
          username: ubuntu
          #passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          
      - name: Verify APP
        run: |
          curl http://localhost:5000
      
